Repository nebius/nebius-solutions-library, pull requests merged in 2025-08, with the labels that each got.

#482 [Soperator] Push IAM tenant/project IDs as VMAgent external labels
  soperator/installations/example/main.tf
  soperator/modules/slurm/main.tf
  soperator/modules/slurm/templates/helm_values/terraform_fluxcd_values.yaml.tftpl
  soperator/modules/slurm/variables.tf
Labels: enhancement

#483 [Soperator] Remove `one` for K8s storage class module
  soperator/installations/example/main.tf
Labels: bug

#485 Forbid clusters without jail submounts and other changes
  soperator/installations/example/main.tf
  soperator/installations/example/terraform.tfvars
  soperator/installations/example/variables.tf
  soperator/modules/available_resources/preset.tf
  soperator/modules/k8s/variables.tf
  soperator/modules/slurm/main.tf
  soperator/modules/slurm/templates/helm_values/terraform_fluxcd_values.yaml.tftpl
  soperator/modules/slurm/variables.tf
Labels: feature
