Repository nebius/nebius-solutions-library, pull requests merged in 2025-03, with the labels that each got.

#215 update ephemeral storage coefficient
  soperator/modules/available_resources/reserve.tf
Labels: bug

#216 Soperator release 1.19.0-1
  modules/gpu-operator/main.tf
  modules/gpu-operator/variables.tf
  soperator/README.md
  soperator/VERSION
  soperator/installations/example/main.tf
  soperator/installations/example/terraform.tfvars
  soperator/installations/example/variables.tf
  soperator/modules/k8s/k8s_ng_accounting.tf
  soperator/modules/k8s/k8s_ng_controller.tf
  soperator/modules/k8s/k8s_ng_login.tf
  soperator/modules/k8s/k8s_ng_system.tf
  soperator/modules/k8s/variables.tf
  soperator/modules/monitoring/templates/helm_values/slurm_monitor.yaml.tftpl
  soperator/modules/monitoring/variables.tf
  soperator/modules/slurm/main.tf
  soperator/modules/slurm/templates/helm_values/slurm_cluster.yaml.tftpl
  soperator/modules/slurm/templates/helm_values/slurm_cluster_storage.yaml.tftpl
  soperator/modules/slurm/templates/motd_nebius_o11y_cm.yaml.tftpl
  soperator/modules/slurm/templates/slurm_epilog_cm.yaml.tftpl
  soperator/modules/slurm/templates/slurm_prolog_cm.yaml.tftpl
  soperator/modules/slurm/templates/spo_values.tftpl
  soperator/modules/slurm/variables.tf
Labels: bug, feature

#238 508: Added values for sconfigcontroller helm
  soperator/modules/slurm/main.tf
  soperator/modules/slurm/templates/helm_values/slurm_cluster.yaml.tftpl
  soperator/modules/slurm/variables.tf
Labels: feature
